[options]
admin_passwd = $pbkdf2-sha512$600000$7/3fG0Po3ZvTmnMuBeAcAw$BYaNJ4WDdJd5koios8P.kSL8Aw3JH3DgGNzIo1KNmb6uO8Wu1KJMzPKifFqR55Wdm5pIttCv/rDDB7O3GrFZAA
db_host = odoo-db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /mnt/extra-addons

