export type invoiceEvent =
  | "INVOICE_RECEIVED"
  | "EXTRACTION_STARTED"
  | "EXTRACTION_COMPLETED"
  | "EXTRACTION_FAILED"
  | "RECONCILIATION_STARTED"
  | "DETERMINISTIC_RECONCILIATION_COMPLETED"
  | "AGENT_INVESTIGATION_STARTED"
  | "RECONCILIATION_COMPLETED";
